question_data = [
  {
    "category": "Science: Computers",
    "type": "boolean",
    "difficulty": "medium",
    "question": "The HTML5 standard was published in 2014.",
    "correct_answer": "True",
    "incorrect_answers": ["False"],
  },
  {
    "category": "Science: Computers",
    "type": "boolean",
    "difficulty": "medium",
    "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
    "correct_answer": "False",
    "incorrect_answers": ["True"],
  },
  {
    "category": "Science: Computers",
    "type": "boolean",
    "difficulty": "easy",
    "question": "The logo for Snapchat is a Bell.",
    "correct_answer": "False",
    "incorrect_answers": ["True"],
  },
  {
    "category": "Science: Computers",
    "type": "boolean",
    "difficulty": "easy",
    "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
    "correct_answer": "False",
    "incorrect_answers": ["True"],
  },
  {
    "category": "Science: Computers",
    "type": "boolean",
    "difficulty": "medium",
    "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
    "correct_answer": "True",
    "incorrect_answers": ["False"],
  },
  {
    "category": "Science: Computers",
    "type": "boolean",
    "difficulty": "easy",
    "question": "Ada Lovelace is often considered the first computer programmer.",
    "correct_answer": "True",
    "incorrect_answers": ["False"],
  },
  {
    "category": "Science: Computers",
    "type": "boolean",
    "difficulty": "medium",
    "question": "MacOS is based on Linux.",
    "correct_answer": "False",
    "incorrect_answers": ["True"],
  },
  {
    "category": "Science: Computers",
    "type": "boolean",
    "difficulty": "easy",
    "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
    "correct_answer": "True",
    "incorrect_answers": ["False"],
  },
  {
    "category": "Science: Computers",
    "type": "boolean",
    "difficulty": "medium",
    "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
    "correct_answer": "True",
    "incorrect_answers": ["False"],
  },
  {
    "category": "Science: Computers",
    "type": "boolean",
    "difficulty": "easy",
    "question": "Linux was first created as an alternative to Windows XP.",
    "correct_answer": "False",
    "incorrect_answers": ["True"],
  },
]